# Generated by Django 3.0.4 on 2020-07-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
