# Generated by Django 3.0.4 on 2020-07-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_s_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
