# Generated by Django 3.0.4 on 2020-07-09 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_articles_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='S_articles',
        ),
    ]
